apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: "master"

  workspaces:
    - name: pipeline-workspace

  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"
      workspaces:
        - name: output  
          workspace: pipeline-workspace
      runAfter:
        - init  

    - name: lint
      taskRef:
        name: echo
      params:
        - name: message
          value: "Linting code with CheckStyle..."
      runAfter:
        - clone

    - name: tests
      taskRef:
        name: echo
      params:
        - name: message
          value: "Running unit tests with Junit..."
      runAfter:
        - lint

    - name: setup-maven
      taskRef:
        name: echo
      params:
        - name: message
          value: "Setting up Maven..."
      runAfter:
        - tests

    - name: build
      taskRef:
        name: echo
      params:
        - name: message
          value: "Building image for $(params.repo-url) ..."
      runAfter:
        - setup-maven

    - name: deploy
      taskRef:
        name: echo
      params:
        - name: message
          value: "Deploying $(params.branch) branch of $(params.repo-url) ..."
      runAfter:
        - build
